GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "gender": "male"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Gusti",
    "email": "gusti@gmail.com",
    "gender": "male"
}

###
DELETE  http://localhost:5000/users/2